ruby "1.9.3"
source 'http://rubygems.org'

gem "less", "~>2.5"
gem "stylus", "~>1.0"
gem "middleman", "~>3.2"
gem "therubyracer", "~>0.12"
gem "middleman-livereload", "~>3.1"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Cross-templating language block fix for Ruby 1.8
platforms :mri_18 do
  gem "ruby18_source_location"
end